name: Package
on:
  push:
    branches:
      - master
    paths:
      - 'CleanArcTemplate.nuspec'
jobs:
  Test:
    name: "Run the unit tests"
    runs-on: ubuntu-latest
    steps:
      
      - name: "run xUnit"
        run: dotnet test --logger "trx;LogFileName=test-results.trx" || true
       
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
         name: Unit Tests
         path: "**/test-results.trx"                            
         reporter: dotnet-trx
         fail-on-error: true


  publish:
    name: Publish to NuGet.org
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: '6.x'

      - name: Create the package
        run: nuget pack CleanArcTemplate.nuspec -NoDefaultExcludes
        
      - name: Publish the package
        run: nuget push *.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}} -SkipDuplicate
